# Generated by Django 5.1.4 on 2025-01-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_department_last_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
